id = "atomizer-theme"
name = "Atomizer Theme"
version = "0.0.1"
schema_version = 1
authors = ["Aris Ripandi"]
description = "Atomizer theme for Zed."
repository = "https://github.com/riipandi/zed-atomizer-theme"
